/**
 * Demo data shown when the backend is unreachable. Every consumer renders a
 * visible "showing sample data" notice so nobody mistakes this for a real
 * record.
 */

import type { PatientSummary } from "./api";
import type { PathwayResult } from "./pathway";

const SAMPLE_PATHWAY: PathwayResult = {
  engine_version: "1.0.0",
  evaluated_at: "2026-09-22T14:12:00Z",
  findings: {
    age: 58,
    sex: "male",
    chief_complaint: "chest tightness when climbing stairs",
    chest_pain: {
      present: true,
      quality: "pressure",
      location: "substernal",
      radiation: [],
      ongoing: false,
      duration_minutes: 5,
      sudden_onset: false,
      exertional: true,
      relieved_by_rest: true,
      relieved_by_nitroglycerin: null,
      positional: false,
      pleuritic: false,
      reproducible_on_palpation: false,
      severity: 4,
      worst_ever: false,
    },
    symptoms: {
      dyspnea: true,
      dyspnea_at_rest: false,
      orthopnea: false,
      diaphoresis: false,
      nausea: false,
      palpitations: false,
      syncope: false,
      presyncope: false,
      leg_swelling: false,
      fatigue: true,
    },
    history: {
      coronary_artery_disease: false,
      prior_myocardial_infarction: false,
      heart_failure: false,
      atrial_fibrillation: null,
      hypertension: true,
      diabetes: false,
      hyperlipidemia: true,
      smoking: false,
      family_history_premature_cad: true,
    },
    vitals: { systolic_bp: 142, diastolic_bp: 88, heart_rate: 78 },
    medications: ["amlodipine", "atorvastatin"],
    notes: null,
  },
  red_flags: [],
  primary_pathway: {
    pathway: "acs",
    name: "Acute coronary syndrome / ischemia",
    score: 61,
    likelihood: "likely",
    disposition: "urgent",
    supporting: [
      "Pressure / squeezing / tightness quality",
      "Substernal location",
      "Brought on by exertion or emotional stress",
      "Relieved by rest",
      "Shortness of breath",
      "Age 58",
      "Male sex",
      "3 cardiovascular risk factors",
    ],
    against: [],
    missing: ["Does the pain spread to your arm, jaw, neck or back?"],
    summary: "Several features of myocardial ischemia are present; ECG and troponin needed.",
  },
  pathways: [],
  chronic_pathways: [
    {
      pathway: "cad_risk",
      name: "Coronary artery disease risk",
      status: "ok",
      probability: 54,
      band: "high",
      chest_pain_type: "typical",
      summary: "Estimated 54% pre-test probability of obstructive CAD (high).",
      guidance: "High pre-test probability — non-invasive ischemia testing or CT coronary angiography is recommended.",
      risk_factors: { diabetes: false, hypertension: true, hyperlipidemia: true, smoking: false, family_history: true },
    },
    {
      pathway: "hypertension_management",
      name: "Hypertension",
      status: "active",
      bp_stage: "stage_2",
      target: "below 130/80 mmHg",
      summary: "Blood pressure stage: stage 2.",
      recommendations: [
        "Medication review — most people at this stage need treatment intensified",
        "Home blood-pressure monitoring: two readings, morning and evening, for 7 days before visits",
        "Limit sodium to under 2 g/day; DASH-style eating pattern",
      ],
    },
    {
      pathway: "diabetes_cardiometabolic",
      name: "Diabetes & cardiometabolic risk",
      status: "not_applicable",
      summary: "No diabetes reported.",
      recommendations: [],
    },
  ],
  disposition: {
    level: "urgent",
    headline: "Go to an emergency department today",
    timeframe: "Within the next few hours",
    patient_message:
      "Your symptoms need to be checked in person today, ideally in an emergency department where an ECG and blood tests can be done. If they get worse at any point, call 911.",
    actions: [
      "Go to the nearest emergency department or urgent care today",
      "Have someone drive you — do not drive yourself",
      "Bring a list of your medications",
      "Call 911 if symptoms worsen on the way",
    ],
    scheduling: "same_day",
    reasons: ["Acute coronary syndrome / ischemia: likely (urgent)"],
    clinician_summary:
      "58y male; chest pain (pressure, substernal, exertional, 5 min) with dyspnea; RF: HTN, HLD. Leading pathway: Acute coronary syndrome / ischemia (likely, score 61). CAD pre-test probability 54%. Disposition: URGENT.",
  },
  next_questions: [],
  risk_percent: 61,
};

export const SAMPLE_PATIENT_SUMMARY: PatientSummary = {
  patient: {
    id: "demo-1",
    name: "Robert Alvarez",
    gender: "male",
    age: 58,
    phone_number: "(555) 014-2231",
    pain_quality: "pressure",
    location: "Yes",
    stress: "No",
    sob: "Yes",
    hypertension: "Yes",
    diabetes: "No",
    hyperlipidemia: "Yes",
    smoking: "No",
    probability: 54,
    created_at: "2026-05-03T09:10:00Z",
  },
  latest_evaluation: {
    id: 4,
    session_id: "session_4_20260922_1412",
    source: "voice",
    patient_id: 1,
    primary_pathway: "acs",
    disposition: "urgent",
    risk_percent: 61,
    result: SAMPLE_PATHWAY,
    created_at: "2026-09-22T14:12:00Z",
  },
  conversations: [
    {
      session_id: "session_4_20260922_1412",
      source: "voice",
      started_at: "2026-09-22T14:03:00Z",
      message_count: 22,
      preview: "I get a tight feeling in my chest when I climb the stairs at work.",
      risk_percent: 61,
      disposition: "urgent",
      primary_pathway: "Acute coronary syndrome / ischemia",
      evaluation_id: 4,
      assessment_complete: true,
    },
    {
      session_id: "session_3_20260830_1830",
      source: "text",
      started_at: "2026-08-30T18:30:00Z",
      message_count: 20,
      preview: "Some pressure in my chest after dinner, went away after twenty minutes.",
      risk_percent: 54,
      disposition: "prompt",
      primary_pathway: "Acute coronary syndrome / ischemia",
      evaluation_id: 3,
      assessment_complete: true,
    },
    {
      session_id: "session_2_20260714_0915",
      source: "text",
      started_at: "2026-07-14T09:15:00Z",
      message_count: 18,
      preview: "My heart was racing last night for about ten minutes.",
      risk_percent: 22,
      disposition: "prompt",
      primary_pathway: "Arrhythmia",
      evaluation_id: 2,
      assessment_complete: true,
    },
  ],
  appointments: [
    {
      id: 11,
      patient_id: 1,
      doctor_id: 2,
      doctor_name: "Dr. Priya Patel",
      scheduled_for: "2026-10-02T10:30:00",
      duration_minutes: 30,
      appointment_type: "urgent",
      status: "scheduled",
      reason: "Exertional chest pressure — ECG and stress testing",
      location: "Riverside Heart Clinic · Suite 210",
      pathway_evaluation_id: 4,
      created_at: "2026-09-22T14:20:00Z",
    },
    {
      id: 9,
      patient_id: 1,
      doctor_id: 2,
      doctor_name: "Dr. Priya Patel",
      scheduled_for: "2026-08-12T15:00:00",
      duration_minutes: 30,
      appointment_type: "follow_up",
      status: "completed",
      reason: "Palpitations follow-up; Holter results",
      location: "Riverside Heart Clinic · Suite 210",
      pathway_evaluation_id: 2,
      created_at: "2026-07-14T09:40:00Z",
    },
  ],
  notes: [
    {
      id: 5,
      patient_id: 1,
      doctor_id: 2,
      author_name: "Dr. Priya Patel",
      note_type: "plan",
      content:
        "Holter showed occasional PACs only — benign. Continue amlodipine. Home BP still running 140s/high 80s; please log twice daily for two weeks before our next visit. Call sooner if the chest tightness happens at rest.",
      visible_to_patient: true,
      created_at: "2026-08-12T15:40:00Z",
    },
    {
      id: 3,
      patient_id: 1,
      doctor_id: 2,
      author_name: "Dr. Priya Patel",
      note_type: "message_to_patient",
      content:
        "Thanks for using the assessment before calling. Your July episode reads as low risk, but keep the 911 guidance in mind if anything changes.",
      visible_to_patient: true,
      created_at: "2026-07-15T08:05:00Z",
    },
  ],
};

export const SAMPLE_TRANSCRIPT = [
  { role: "assistant" as const, content: "Hi Robert, I'm Agilance. I can help you think through what you're feeling. Can you tell me what's been going on?" },
  { role: "user" as const, content: "I get a tight feeling in my chest when I climb the stairs at work." },
  { role: "assistant" as const, content: "Thank you. Does the tightness feel like pressure, sharp, burning, or dull?" },
  { role: "user" as const, content: "Pressure, right in the middle." },
  { role: "assistant" as const, content: "Does it ease within a few minutes when you rest?" },
  { role: "user" as const, content: "Yes, usually after five minutes or so." },
  { role: "assistant" as const, content: "Are you short of breath, sweating, or feeling sick with it?" },
  { role: "user" as const, content: "A bit breathless, no sweating or nausea." },
  { role: "assistant" as const, content: "Based on what you've shared, this needs to be checked today — ideally in an emergency department where an ECG and blood tests can be done. I've saved a summary for your care team and can help you schedule a follow-up." },
];
